#print("hello what is your first name")
first_name =input("hello what is your first name?:")
#print("and what is your last name")
last_name =input("and what is your last name?:")
print("Nice to meet you",first_name,last_name)
