age_str = str(input("please tell me your age:"))
age_int = int(age_str)
print(f"You are currently {age_int} years old")
print(f"In 10 years you'll be { age_int+ 10}")
print(f"In 20 years you'll be { age_int+ 20}")
print(f"In 30 years you'll be { age_int+ 30}")